/**
 * Role-Based Access Control Constants
 * The Bharmals Kitchen — Restaurant Management System
 */

export const ROLES = {
  OWNER: 'Owner',
  ADMIN: 'Admin',
  MANAGER: 'Manager',
  CASHIER: 'Cashier',
  CHEF: 'Chef',
  KITCHEN_STAFF: 'Kitchen Staff',
  WAITER: 'Waiter',
  CAPTAIN: 'Captain',
  INVENTORY_MANAGER: 'Inventory Manager',
  ACCOUNTANT: 'Accountant',
  STAFF: 'Staff',
  CUSTOMER: 'Customer',
};

export const PERMISSIONS = {
  VIEW_DASHBOARD: 'view_dashboard',
  CREATE_ORDER: 'create_order',
  EDIT_ORDER: 'edit_order',
  CANCEL_ORDER: 'cancel_order',
  APPLY_DISCOUNT: 'apply_discount',
  OVERRIDE_PRICE: 'override_price',
  REFUND_ORDER: 'refund_order',
  MANAGE_MENU: 'manage_menu',
  MANAGE_RECIPE: 'manage_recipe',
  MANAGE_INVENTORY: 'manage_inventory',
  ADJUST_STOCK: 'adjust_stock',
  MANAGE_PURCHASE: 'manage_purchase',
  MANAGE_SUPPLIER: 'manage_supplier',
  MANAGE_STAFF: 'manage_staff',
  MANAGE_ATTENDANCE: 'manage_attendance',
  MANAGE_SALARY: 'manage_salary',
  VIEW_REPORTS: 'view_reports',
  EXPORT_REPORTS: 'export_reports',
  MANAGE_SETTINGS: 'manage_settings',
  MANAGE_PRINTERS: 'manage_printers',
  MANAGE_USERS: 'manage_users',
  VIEW_AUDIT_LOGS: 'view_audit_logs',
  CLOSE_DAY: 'close_day',
  MANAGE_TABLES: 'manage_tables',
  MANAGE_RESERVATIONS: 'manage_reservations',
  MANAGE_CUSTOMERS: 'manage_customers',
  MANAGE_LOYALTY: 'manage_loyalty',
  MANAGE_PROMOTIONS: 'manage_promotions',
  MANAGE_EXPENSES: 'manage_expenses',
  VIEW_KITCHEN: 'view_kitchen',
  UPDATE_KITCHEN: 'update_kitchen',
  MANAGE_BRANCHES: 'manage_branches',
  VIEW_FINANCIALS: 'view_financials',
};

/**
 * Default permission assignments per role.
 * These serve as templates — actual permissions are stored in Firestore
 * and are fully configurable per organization.
 */
export const DEFAULT_ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS), // All permissions

  [ROLES.ADMIN]: Object.values(PERMISSIONS), // All permissions

  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.EDIT_ORDER,
    PERMISSIONS.CANCEL_ORDER,
    PERMISSIONS.APPLY_DISCOUNT,
    PERMISSIONS.OVERRIDE_PRICE,
    PERMISSIONS.REFUND_ORDER,
    PERMISSIONS.MANAGE_MENU,
    PERMISSIONS.MANAGE_RECIPE,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.ADJUST_STOCK,
    PERMISSIONS.MANAGE_PURCHASE,
    PERMISSIONS.MANAGE_SUPPLIER,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.MANAGE_ATTENDANCE,
    PERMISSIONS.MANAGE_SALARY,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.MANAGE_PRINTERS,
    PERMISSIONS.CLOSE_DAY,
    PERMISSIONS.MANAGE_TABLES,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.MANAGE_LOYALTY,
    PERMISSIONS.MANAGE_PROMOTIONS,
    PERMISSIONS.MANAGE_EXPENSES,
    PERMISSIONS.VIEW_KITCHEN,
    PERMISSIONS.UPDATE_KITCHEN,
    PERMISSIONS.VIEW_FINANCIALS,
  ],

  [ROLES.CASHIER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.EDIT_ORDER,
    PERMISSIONS.CANCEL_ORDER,
    PERMISSIONS.MANAGE_TABLES,
    PERMISSIONS.CLOSE_DAY,
  ],

  [ROLES.CHEF]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_KITCHEN,
    PERMISSIONS.UPDATE_KITCHEN,
    PERMISSIONS.MANAGE_RECIPE,
    PERMISSIONS.MANAGE_MENU, // For category management
    PERMISSIONS.MANAGE_INVENTORY, // For raw materials availability
  ],

  [ROLES.KITCHEN_STAFF]: [
    PERMISSIONS.VIEW_KITCHEN,
    PERMISSIONS.UPDATE_KITCHEN,
  ],

  [ROLES.WAITER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.EDIT_ORDER,
    PERMISSIONS.MANAGE_TABLES,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.MANAGE_CUSTOMERS,
  ],

  [ROLES.CAPTAIN]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.CREATE_ORDER,
    PERMISSIONS.EDIT_ORDER,
    PERMISSIONS.MANAGE_TABLES,
    PERMISSIONS.MANAGE_RESERVATIONS,
    PERMISSIONS.MANAGE_CUSTOMERS,
  ],

  [ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_INVENTORY,
    PERMISSIONS.ADJUST_STOCK,
    PERMISSIONS.MANAGE_PURCHASE,
    PERMISSIONS.MANAGE_SUPPLIER,
    PERMISSIONS.MANAGE_RECIPE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.EXPORT_REPORTS,
    PERMISSIONS.MANAGE_EXPENSES,
    PERMISSIONS.MANAGE_SALARY,
    PERMISSIONS.VIEW_FINANCIALS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
  ],

  [ROLES.STAFF]: [
    PERMISSIONS.VIEW_DASHBOARD,
  ],

  [ROLES.CUSTOMER]: [
    PERMISSIONS.CREATE_ORDER,
  ],
};
